#ifndef SERIALIZABLE_STRUCT_START
#include "shared/serialization/define_serialization_macros.h"
#endif

SERIALIZABLE_STRUCT_START(Position)
    SERIALIZABLE_FIELD(float, x)
    SERIALIZABLE_FIELD(float, y)
    SERIALIZABLE_FIELD(float, z)
SERIALIZABLE_STRUCT_END(Position)

SERIALIZABLE_STRUCT_START(TRS)
    SERIALIZABLE_FIELD(Position, position)
    SERIALIZABLE_FIELD(Position, rotation)
    SERIALIZABLE_FIELD(Position, scale)
SERIALIZABLE_STRUCT_END(TRS)

SERIALIZABLE_STRUCT_START(M44)
    SERIALIZABLE_FIXED_ARRAY(float, m, 16)
SERIALIZABLE_STRUCT_END(M44)

SERIALIZABLE_STRUCT_START(FixedArrayTest)
    SERIALIZABLE_FIXED_ARRAY(Position, positions, 3)
SERIALIZABLE_STRUCT_END(FixedArrayTest)

SERIALIZABLE_STRUCT_START(DynamicArrayTest)
    SERIALIZABLE_STRUCT_LIST_ELEMENT(M44, matrices)
SERIALIZABLE_STRUCT_END(DynamicArrayTest)


SERIALIZABLE_STRUCT_START(TestComponent)
    SERIALIZABLE_FIELD(TRS, trs)
SERIALIZABLE_STRUCT_END(TestComponent)