
#define PSGID(t) psg.t##Id
#define ID(t) PSGID(t)
#define REGISTRATION_NAME2(t) t##Register
#define REGISTRATION_NAME(t) REGISTRATION_NAME2(t)
#define STRINGIFY2(x) #x
#define STRINGIFY(x) STRINGIFY2(x)
#define COMPONENT_NAME_STRING(COMPONENT_NAME) STRINGIFY(COMPONENT_NAME)
#define REGISTER_COMPONENT(COMPONENT_NAME) ID(COMPONENT_NAME) = SceneGraph_registerComponentType(psg.sceneGraph, COMPONENT_NAME_STRING(COMPONENT_NAME), sizeof(COMPONENT_NAME), (SceneComponentTypeMethods)
#define BEGIN_COMPONENT_REGISTRATION(T) void REGISTRATION_NAME(T)() { REGISTER_COMPONENT (T)
#define END_COMPONENT_REGISTRATION );}

#define COMPONENT_STRUCT_NAME(t) t
#define BEGIN_COMPONENT_STRUCT typedef struct COMPONENT_STRUCT_NAME(COMPONENT_NAME)
#define END_COMPONENT_STRUCT COMPONENT_STRUCT_NAME(COMPONENT_NAME);