#ifndef SERIALIZABLE_STRUCT_START
#include "shared/serialization/define_serialization_macros.h"
#endif


#define EMPTY_STRUCT(name) SERIALIZABLE_STRUCT_START(name) SERIALIZABLE_STRUCT_END(name)
EMPTY_STRUCT(int)
EMPTY_STRUCT(float)
EMPTY_STRUCT(double)
EMPTY_STRUCT(char)
EMPTY_STRUCT(uint8_t)
EMPTY_STRUCT(uint16_t)
EMPTY_STRUCT(uint32_t)
EMPTY_STRUCT(int8_t)
EMPTY_STRUCT(int16_t)
EMPTY_STRUCT(int32_t)
EMPTY_STRUCT(size_t)
#undef EMPTY_STRUCT

SERIALIZABLE_STRUCT_START(Vector3)
    SERIALIZABLE_FIELD(float, x)
    SERIALIZABLE_FIELD(float, y)
    SERIALIZABLE_FIELD(float, z)
SERIALIZABLE_STRUCT_END(Vector3)

SERIALIZABLE_STRUCT_START(Vector2)
    SERIALIZABLE_FIELD(float, x)
    SERIALIZABLE_FIELD(float, y)
SERIALIZABLE_STRUCT_END(Vector2)

SERIALIZABLE_STRUCT_START(Rectangle)
    SERIALIZABLE_FIELD(float, x)
    SERIALIZABLE_FIELD(float, y)
    SERIALIZABLE_FIELD(float, width)
    SERIALIZABLE_FIELD(float, height)
SERIALIZABLE_STRUCT_END(Rectangle)

SERIALIZABLE_STRUCT_START(Color)
    SERIALIZABLE_FIELD(uint8_t, r)
    SERIALIZABLE_FIELD(uint8_t, g)
    SERIALIZABLE_FIELD(uint8_t, b)
    SERIALIZABLE_FIELD(uint8_t, a)
SERIALIZABLE_STRUCT_END(Color)

SERIALIZABLE_STRUCT_START(Camera3D)
    SERIALIZABLE_FIELD(Vector3, position)
    SERIALIZABLE_FIELD(Vector3, target)
    SERIALIZABLE_FIELD(Vector3, up)
    SERIALIZABLE_FIELD(float, fovy)
SERIALIZABLE_STRUCT_END(Camera3D)