#ifndef _ANIMATION_CONDITIONS_H_
#define _ANIMATION_CONDITIONS_H_

#define ANIMATION_CONDITION_TYPE_NONE 0
#define ANIMATION_CONDITION_TYPE_EQUALS 1
#define ANIMATION_CONDITION_TYPE_NOT_EQUALS 2
#define ANIMATION_CONDITION_TYPE_GREATER_THAN 3
#define ANIMATION_CONDITION_TYPE_LESS_THAN 4
#define ANIMATION_CONDITION_TYPE_GREATER_THAN_OR_EQUALS 5
#define ANIMATION_CONDITION_TYPE_LESS_THAN_OR_EQUALS 6

#endif